# App name
spring.application.name=lady-shoe-mart

# Server Configuration
server.port=8000

# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# AWS S3 Configuration
amazon.aws.access-key=${AWS_ACCESS_KEY}
amazon.aws.secret-key=${AWS_SECRET_KEY}
amazon.aws.region=${AWS_REGION}
amazon.aws.bucket-name=${AWS_BUCKET_NAME}



